var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(e,n,p){if(e==Array.prototype||e==Object.prototype)return e;e[n]=p.value;return e};
$jscomp.getGlobal=function(e){e=["object"==typeof globalThis&&globalThis,e,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var n=0;n<e.length;++n){var p=e[n];if(p&&p.Math==Math)return p}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(e,n){var p=$jscomp.propertyToPolyfillSymbol[n];if(null==p)return e[n];p=e[p];return void 0!==p?p:e[n]};$jscomp.polyfill=function(e,n,p,w){n&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(e,n,p,w):$jscomp.polyfillUnisolated(e,n,p,w))};
$jscomp.polyfillUnisolated=function(e,n,p,w){p=$jscomp.global;e=e.split(".");for(w=0;w<e.length-1;w++){var u=e[w];if(!(u in p))return;p=p[u]}e=e[e.length-1];w=p[e];n=n(w);n!=w&&null!=n&&$jscomp.defineProperty(p,e,{configurable:!0,writable:!0,value:n})};
$jscomp.polyfillIsolated=function(e,n,p,w){var u=e.split(".");e=1===u.length;w=u[0];w=!e&&w in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var y=0;y<u.length-1;y++){var q=u[y];if(!(q in w))return;w=w[q]}u=u[u.length-1];p=$jscomp.IS_SYMBOL_NATIVE&&"es6"===p?w[u]:null;n=n(p);null!=n&&(e?$jscomp.defineProperty($jscomp.polyfills,u,{configurable:!0,writable:!0,value:n}):n!==p&&($jscomp.propertyToPolyfillSymbol[u]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(u):$jscomp.POLYFILL_PREFIX+u,u=
$jscomp.propertyToPolyfillSymbol[u],$jscomp.defineProperty(w,u,{configurable:!0,writable:!0,value:n})))};$jscomp.polyfill("Math.imul",function(e){return e?e:function(n,p){n=Number(n);p=Number(p);var w=n&65535,u=p&65535;return w*u+((n>>>16&65535)*u+w*(p>>>16&65535)<<16>>>0)|0}},"es6","es3");
$jscomp.polyfill("Math.fround",function(e){if(e)return e;if($jscomp.SIMPLE_FROUND_POLYFILL||"function"!==typeof Float32Array)return function(p){return p};var n=new Float32Array(1);return function(p){n[0]=p;return n[0]}},"es6","es3");$jscomp.arrayIteratorImpl=function(e){var n=0;return function(){return n<e.length?{done:!1,value:e[n++]}:{done:!0}}};$jscomp.arrayIterator=function(e){return{next:$jscomp.arrayIteratorImpl(e)}};
$jscomp.makeIterator=function(e){var n="undefined"!=typeof Symbol&&Symbol.iterator&&e[Symbol.iterator];return n?n.call(e):$jscomp.arrayIterator(e)};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(e){function n(){this.batch_=null}function p(q){return q instanceof u?q:new u(function(c,a){c(q)})}if(e&&!$jscomp.FORCE_POLYFILL_PROMISE)return e;n.prototype.asyncExecute=function(q){if(null==this.batch_){this.batch_=[];var c=this;this.asyncExecuteFunction(function(){c.executeBatch_()})}this.batch_.push(q)};var w=$jscomp.global.setTimeout;n.prototype.asyncExecuteFunction=function(q){w(q,0)};n.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var q=
this.batch_;this.batch_=[];for(var c=0;c<q.length;++c){var a=q[c];q[c]=null;try{a()}catch(d){this.asyncThrow_(d)}}}this.batch_=null};n.prototype.asyncThrow_=function(q){this.asyncExecuteFunction(function(){throw q;})};var u=function(q){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var c=this.createResolveAndReject_();try{q(c.resolve,c.reject)}catch(a){c.reject(a)}};u.prototype.createResolveAndReject_=function(){function q(d){return function(g){a||(a=!0,d.call(c,g))}}var c=this,a=!1;
return{resolve:q(this.resolveTo_),reject:q(this.reject_)}};u.prototype.resolveTo_=function(q){if(q===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(q instanceof u)this.settleSameAsPromise_(q);else{a:switch(typeof q){case "object":var c=null!=q;break a;case "function":c=!0;break a;default:c=!1}c?this.resolveToNonPromiseObj_(q):this.fulfill_(q)}};u.prototype.resolveToNonPromiseObj_=function(q){var c=void 0;try{c=q.then}catch(a){this.reject_(a);return}"function"==typeof c?
this.settleSameAsThenable_(c,q):this.fulfill_(q)};u.prototype.reject_=function(q){this.settle_(2,q)};u.prototype.fulfill_=function(q){this.settle_(1,q)};u.prototype.settle_=function(q,c){if(0!=this.state_)throw Error("Cannot settle("+q+", "+c+"): Promise already settled in state"+this.state_);this.state_=q;this.result_=c;this.executeOnSettledCallbacks_()};u.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var q=0;q<this.onSettledCallbacks_.length;++q)y.asyncExecute(this.onSettledCallbacks_[q]);
this.onSettledCallbacks_=null}};var y=new n;u.prototype.settleSameAsPromise_=function(q){var c=this.createResolveAndReject_();q.callWhenSettled_(c.resolve,c.reject)};u.prototype.settleSameAsThenable_=function(q,c){var a=this.createResolveAndReject_();try{q.call(c,a.resolve,a.reject)}catch(d){a.reject(d)}};u.prototype.then=function(q,c){function a(b,f){return"function"==typeof b?function(k){try{d(b(k))}catch(l){g(l)}}:f}var d,g,x=new u(function(b,f){d=b;g=f});this.callWhenSettled_(a(q,d),a(c,g));return x};
u.prototype.catch=function(q){return this.then(void 0,q)};u.prototype.callWhenSettled_=function(q,c){function a(){switch(d.state_){case 1:q(d.result_);break;case 2:c(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?y.asyncExecute(a):this.onSettledCallbacks_.push(a)};u.resolve=p;u.reject=function(q){return new u(function(c,a){a(q)})};u.race=function(q){return new u(function(c,a){for(var d=$jscomp.makeIterator(q),g=d.next();!g.done;g=d.next())p(g.value).callWhenSettled_(c,
a)})};u.all=function(q){var c=$jscomp.makeIterator(q),a=c.next();return a.done?p([]):new u(function(d,g){function x(k){return function(l){b[k]=l;f--;0==f&&d(b)}}var b=[],f=0;do b.push(void 0),f++,p(a.value).callWhenSettled_(x(b.length-1),g),a=c.next();while(!a.done)})};return u},"es6","es3");
(function(){function e(){this.i0=0;this.d=[this]}function n(c,a,d,g,x){var b,f;var k=p([],0,8192,y);if(4>(d|0)){if(0===(d|0))return 0;g[x]=d+255|0;if((((a+d|0)+-2|0)+1|0)>=a)for(b=f=0;;)if(b=b+1|0,g[x+b|0]=c[a+f|0]|0,(a+f|0)<=((a+d|0)+-2|0))f=f+1|0;else break;return d+1|0}for(b=0;k[b]={d:c,o:a},b=b+1|0,8192>(0+b|0););g[x]=31;g[x+1|0]=c[a]|0;g[x+2|0]=c[a+1|0]|0;if((a+2|0)<((a+d|0)+-12|0)){var l=2;f=3;for(b=2;;){a:{var h=b+1|0;var m=c[a+h|0]&255;var v=m<<8|c[a+b|0]&255;var t=c[(a+b|0)+2|0]|0;var r=
k[(v>>>3^v^(t<<8|m))&8191];var z=r.o;var A=a+b|0;var B=A-z|0;k[(v>>>3^v^(t<<8|m))&8191]={d:c,o:a+b|0};if((A|0)===(z|0)||8191<B>>>0)b=c[a+b|0]|0;else if(m=r.d[r.o]|0,v=c[a+b|0]|0,(m&255)===(v&255))if((r.d[r.o+1|0]|0)===(c[a+h|0]&255))if(v=r.d[r.o+2|0]|0,v===(c[(a+b|0)+2|0]|0)){m=B-1|0;t=b+3|0;b:if(0===(m|0))if((a+t|0)<((a+d|0)+-2|0))for(h=3,b=0;;){z=t+b|0;if((r.d[r.o+h|0]&255)===v)if(b=b+1|0,z=t+b|0,h=h+1|0,(a+z|0)<((a+d|0)+-2|0))continue;else h=z;else{h=z;break b}break}else h=t;else if(h=b+4|0,(r.d[r.o+
3|0]|0)===(c[a+t|0]&255))if(v=b+5|0,(r.d[r.o+4|0]|0)===(c[a+h|0]&255)){if(h=b+6|0,(r.d[r.o+5|0]|0)===(c[a+v|0]&255))if(v=b+7|0,(r.d[r.o+6|0]|0)===(c[a+h|0]&255)){if(h=b+8|0,(r.d[r.o+7|0]|0)===(c[a+v|0]&255))if(v=b+9|0,(r.d[r.o+8|0]|0)===(c[a+h|0]&255)){if(h=b+10|0,(r.d[r.o+9|0]|0)===(c[a+v|0]&255))if(v=b+11|0,(r.d[r.o+10|0]|0)===(c[a+h|0]&255))for(h=0,b=11;;){t=v+h|0;if((a+t|0)<((a+d|0)+-2|0)){if(z=h+1|0,h=v+z|0,B=b+1|0,(r.d[r.o+b|0]&255)===(c[a+t|0]&255)){h=z;b=B;continue}}else h=t;break}else h=
v}else h=v}else h=v}else h=v;0===(l|0)?f=f-1|0:g[((x+f|0)+(-l|0)|0)+-1|0]=l+255|0;l=(a+h|0)+-3|0;b=l-A|0;if(262<b>>>0){v=((-263-A|0)+l>>>0)/262|0;l=((l-262|0)-A|0)+(w(v,-262)|0)|0;t=x+f|0;for(r=g;;)if(r[t]=(m>>>8)+224|0,r[t+1|0]=253,r[t+2|0]=m,b=b-262|0,262<b>>>0)t=t+3|0;else break;b=f+3|0;f=b+(w(v,3)|0)|0;b=l}7>b>>>0?(g[x+f|0]=(b<<5)+(m>>>8)|0,t=(x+f|0)+2|0,r=g,b=m,l=2):(g[x+f|0]=(m>>>8)+224|0,g[(x+f|0)+2|0]=m,t=(x+f|0)+3|0,r=g,l=3,b=b+249|0);g[(x+f|0)+1|0]=b;f=f+l|0;l=c[(a+h|0)+-2|0]&255;m=l<<8|
c[(a+h|0)+-3|0]&255;b=h-1|0;k[(m>>>3^m^((c[a+b|0]&255)<<8|l))&8191]={d:c,o:(a+h|0)+-3|0};l=c[a+b|0]&255;m=l<<8|c[(a+h|0)+-2|0]&255;k[(m>>>3^m^((c[a+h|0]&255)<<8|l))&8191]={d:c,o:(a+h|0)+-2|0};r[t]=31;f=f+1|0;l=0;break a}else b=m;else b=m;else b=v;g[x+f|0]=b;l=l+1|0;b=f+1|0;32===(l|0)?(g[x+b|0]=31,f=f+2|0,b=h,l=0):(f=b,b=h)}if(!((a+b|0)<((a+d|0)+-12|0)))break}}else l=2,f=3,b=2;if((a+b|0)<=(((a+d|0)+-2|0)+1|0))for(;;)if(g[x+f|0]=c[a+b|0]|0,l=l+1|0,h=f+1|0,32===(l|0)?(g[x+h|0]=31,f=f+2|0,l=0):f=h,h=
b+1|0,(a+b|0)<=((a+d|0)+-2|0))b=h;else break;0===(l|0)?f=f-1|0:g[((x+f|0)+(-l|0)|0)+-1|0]=l+255|0;return(x+f|0)-x|0}function p(c,a,d,g){for(;a<d;a++)c[a]=g;return c}var w=Math.imul,u=Math.fround;e.prototype.encode=function(c){var a=+c.length;var d=0>a?-a:a;var g=~~(d*u(2.32830644E-10));var x=new Int32Array(4);x[0]=g;d=~~(d%4294967296);x[1]=d;x[2]=0!==(d|0)?g^-1|0:-g|0;x[3]=-d|0;g=x[(0>a?2:0)+1|0]|0;x=new Uint8Array(g+1|0);n(c,0,g,x,0)|0;if(65536>(g|0))c=n(c,0,g,x,0)|0;else{d=x;var b;var f=p([],0,
8192,y);if(4>(g|0))if(0===(g|0))c=0;else{d[0]=g+255|0;if(0<=(((0+g|0)+-2|0)+1|0))for(a=b=0;;)if(a=a+1|0,d[0+a|0]=c[0+b|0]|0,(0+b|0)<=((0+g|0)+-2|0))b=b+1|0;else break;c=g+1|0}else{for(a=0;f[a]={d:c,o:0},a=a+1|0,8192>(0+a|0););d[0]=31;d[1]=c[0]|0;d[2]=c[1]|0;if(2<((0+g|0)+-12|0)){var k=2;b=3;for(a=2;;){c:{d:{var l=c[0+a|0]|0;if((l&255)===(c[(0+a|0)+-1|0]&255)){l&=255;var h=c[(0+a|0)+1|0]|0;var m=c[(0+a|0)+2|0]|0;if((l<<8|l|0)===(m<<8|h|0)){var v=(0+a|0)+2|0;var t=c;m=3;l=1;break d}}else h=c[(0+a|0)+
1|0]|0,m=c[(0+a|0)+2|0]|0,l&=255;var r=h<<8|l;t=f[(r^(m<<8|h))&8191^r>>>3];var z=t.o;var A=0+a|0;l=A-z|0;f[(r^(m<<8|h))&8191^r>>>3]={d:c,o:0+a|0};m=a+1|0;if((A|0)===(z|0)||73724<l>>>0)a=c[0+a|0]|0;else if(h=t.d[t.o]|0,r=c[0+a|0]|0,(h&255)===(r&255))if((t.d[t.o+1|0]|0)===(c[0+m|0]&255))if((t.d[t.o+2|0]|0)===(c[(0+a|0)+2|0]|0))if(8190<l>>>0)if((c[(0+a|0)+3|0]|0)===(t.d[t.o+3|0]|0))if((c[(0+a|0)+4|0]|0)===(t.d[t.o+4|0]|0)){m=5;v=t.o+5|0;t=t.d;break d}else a=h;else a=h;else{m=3;v=t.o+3|0;t=t.d;break d}else a=
h;else a=h;else a=r;d[0+b|0]=a;k=k+1|0;a=b+1|0;32===(k|0)?(d[0+a|0]=31,b=b+2|0,a=m,k=0):(b=a,a=m);break c}z=a+m|0;A=l-1|0;d:if(0===(A|0))if(h=c[(0+z|0)+-1|0]|0,(0+z|0)<((0+g|0)+-2|0))for(m=0;;){if((t[v]&255)===(h&255)){if(m=m+1|0,((0+z|0)+m|0)<((0+g|0)+-2|0)){v=v+1|0;continue}}else break d;break}else m=0;else if((t[v]&255)===(c[0+z|0]&255)){if(m=2,(t[v+1|0]|0)===(c[(0+z|0)+1|0]|0))if(h=m+1|0,(t[v+2|0]|0)===(c[(0+z|0)+m|0]&255)){if(m=h+1|0,(t[v+3|0]|0)===(c[(0+z|0)+h|0]&255))if(h=m+1|0,(t[v+4|0]|0)===
(c[(0+z|0)+m|0]&255)){if(m=h+1|0,(t[v+5|0]|0)===(c[(0+z|0)+h|0]&255))if(h=m+1|0,(t[v+6|0]|0)===(c[(0+z|0)+m|0]&255)){if(m=h+1|0,(t[v+7|0]|0)===(c[(0+z|0)+h|0]&255))for(r=m,m=h,h=0;;){if(((0+z|0)+r|0)<((0+g|0)+-2|0)){m=m+2|0;var B=h+1|0;if((t[(v+8|0)+h|0]&255)===(c[(0+z|0)+r|0]&255)){var C=m;h=B;m=r;r=C;continue}}else m=r;break}}else m=h}else m=h}else m=h}else m=1;m=z+m|0;0===(k|0)?b=b-1|0:d[((0+b|0)+(-k|0)|0)+-1|0]=k+255|0;h=(0+m|0)+-3|0;r=0+a|0;k=h-r|0;if(8191>A>>>0)if(7>k>>>0)d[0+b|0]=(k<<5)+(A>>>
8)|0,d[(0+b|0)+1|0]=A,a=b+2|0;else{d[0+b|0]=(A>>>8)+224|0;a=b+1|0;k=k-7|0;if(254<k>>>0){for(l=(-262-r|0)+h|0;;)if(d[0+a|0]=255,b=b+2|0,k=k-255|0,254<k>>>0)h=a,a=b,b=h;else break;v=0+b|0;t=d;k=(l>>>0)%255|0}else v=0+a|0,t=d,a=b;t[v]=k;d[(0+a|0)+2|0]=A;a=a+3|0}else if(l=l-8192|0,7>k>>>0)d[0+b|0]=(k<<5)+31|0,d[(0+b|0)+1|0]=255,d[(0+b|0)+2|0]=l>>>8,d[(0+b|0)+3|0]=l,a=b+4|0;else{d[0+b|0]=255;a=b+1|0;k=k-7|0;if(254<k>>>0){for(h=(-262-r|0)+h|0;;)if(d[0+a|0]=255,b=b+2|0,k=k-255|0,254<k>>>0)r=a,a=b,b=r;else break;
v=0+b|0;t=d;k=(h>>>0)%255|0}else v=0+a|0,t=d,a=b;t[v]=k;d[(0+a|0)+2|0]=255;d[(0+a|0)+3|0]=l>>>8;d[(0+a|0)+4|0]=l;a=a+5|0}b=c[(0+m|0)+-2|0]&255;k=b<<8|c[(0+m|0)+-3|0]&255;l=m-1|0;f[(k>>>3^k^((c[0+l|0]&255)<<8|b))&8191]={d:c,o:(0+m|0)+-3|0};b=c[0+l|0]&255;k=b<<8|c[(0+m|0)+-2|0]&255;f[(k>>>3^k^((c[0+m|0]&255)<<8|b))&8191]={d:c,o:(0+m|0)+-2|0};d[0+a|0]=31;b=a+1|0;a=l;k=0}if(!((0+a|0)<((0+g|0)+-12|0)))break}}else k=2,b=3,a=2;if((0+a|0)<=(((0+g|0)+-2|0)+1|0))for(;;)if(d[0+b|0]=c[0+a|0]|0,k=k+1|0,l=b+1|
0,32===(k|0)?(d[0+l|0]=31,b=b+2|0,k=0):b=l,l=a+1|0,(0+a|0)<=((0+g|0)+-2|0))a=l;else break;0===(k|0)?b=b-1|0:d[((0+b|0)+(-k|0)|0)+-1|0]=k+255|0;d[0]|=32;c=0+b|0}c|=0}g=c;new Number(+(g|0));c=new Uint8Array(g/1|0);if(0!==(g|0))for(d=0;c[d]=x[d]|0,d=d+1|0,(g|0)!==(d|0););g=0;x=c;+x.BYTES_PER_ELEMENT;0!==(g|0)&&(x=x.subarray(+(g>>>0)));return x};e.prototype.decode=function(c){var a=+c.length;var d=0>a?-a:a;var g=~~(d*u(2.32830644E-10));var x=new Int32Array(4);x[0]=g;d=~~(d%4294967296);x[1]=d;x[2]=0!==
(d|0)?g^-1|0:-g|0;x[3]=-d|0;d=0>a?2:0;g=x[d]|0;d=x[d+1|0]|0;x=new Number(4294967296*+(g>>>0)+ +(d>>>0));x.toString(10);x=new Uint8Array(10485760);switch((c[0]&255)>>>5|0){case 1:b:{g=d;d=x;var b,f;a=c[0]&31;var k=f=1;for(b=0;;){if(31<a>>>0){var l=a<<8&7936;var h=(a>>>5)-1|0;if(6===(h|0))for(h=6;;){var m=c[0+f|0]|0;h=(m&255)+h|0;var v=f+1|0;if(255===(m&255))f=f+1|0;else{f=v;break}}v=c[0+f|0]|0;m=f+1|0;if(7936===(l|0)&&255===(v&255)){l=c[0+m|0]|0;v=c[(0+f|0)+2|0]|0;m=f+3|0;var t=((0+b|0)+(-(((l&255)<<
8)+v|0)|0)|0)+-8191|0;var r=d;l=3}else t=((0+b|0)+(-l|0)|0)+(-(v&255)|0)|0,r=d,l=1;if(10485760<(((0+b|0)+h|0)+3|0)||0>(t+-1|0)){c=0;break b}(0+m|0)<(0+g|0)?(f=f+l|0,a=c[0+m|0]&255,m=f+1|0):k=0;v=r[t+-1|0]|0;d[0+b|0]=v;if(r.length===d.length&&r===d&&t===(0+b|0)){if(d[(0+b|0)+1|0]=v,d[(0+b|0)+2|0]=v,b=b+3|0,0!==(h|0)){f=h;for(l=0;;)if(d[(0+b|0)+l|0]=v,f=f-1|0,0!==(f|0))l=l+1|0;else break;b=b+h|0}}else if(d[(0+b|0)+1|0]=r[t]|0,d[(0+b|0)+2|0]=r[t+1|0]|0,b=b+3|0,0!==(h|0)){f=h;for(l=v=0;;)if(d[(0+b|0)+
v|0]=r[(t+2|0)+l|0]|0,f=f-1|0,0!==(f|0))v=v+1|0,l=l+1|0;else break;b=b+h|0}f=m}else{k=a+1|0;if(10485760<((0+b|0)+k|0)||((0+f|0)+k|0)>(0+g|0)){c=0;break b}d[0+b|0]=c[0+f|0]|0;h=f+1|0;l=b+1|0;if(0===(a|0))a=f,f=h,h=a,b=l;else for(k=b;;)if(d[0+l|0]=c[0+h|0]|0,f=f+2|0,a=a-1|0,b=k+2|0,0!==(a|0))b=k,m=f,f=h,h=m,k=l,l=b+2|0;else break;k=(a=(0+f|0)<(0+g|0)?1:0)?1:0;a?(a=c[0+f|0]&255,f=h+2|0):a=0}if(0===(k|0))break}c=0+b|0}g=c|0;break;case 0:b:{g=d;d=x;k=c[0]&31;b=f=1;for(a=0;;){if(31<k>>>0){h=(k>>>5)-1|0;
6===(h|0)&&(h=(c[0+b|0]&255)+6|0,b=b+1|0);m=-(c[0+b|0]&255)|0;if(10485760<(((0+a|0)+h|0)+3|0)){c=0;break b}r=m-1|0;if(0>(((0+a|0)+(-(k<<8&7936)|0)|0)+r|0)){c=0;break b}l=b+1|0;(0+l|0)<(0+g|0)?(l=c[0+l|0]&255,b=b+2|0,t=f,f=l,l=t):(f=k,b=l,l=0);if(d.length===d.length&&d===d&&(((0+a|0)+(-(k<<8&7936)|0)|0)+m|0)===(0+a|0)){r=d[((0+a|0)+(-(k<<8&7936)|0)|0)+r|0]|0;d[0+a|0]=r;d[(0+a|0)+1|0]=r;d[(0+a|0)+2|0]=r;a=a+3|0;if(0!==(h|0)){k=h;for(m=0;;)if(d[(0+a|0)+m|0]=r,k=k-1|0,0!==(k|0))m=m+1|0;else break;a=a+
h|0}k=f;f=l}else{m=r+1|0;d[0+a|0]=d[((0+a|0)+(-(k<<8&7936)|0)|0)+r|0]|0;t=m+1|0;d[(0+a|0)+1|0]=d[((0+a|0)+(-(k<<8&7936)|0)|0)+m|0]|0;d[(0+a|0)+2|0]=d[((0+a|0)+(-(k<<8&7936)|0)|0)+t|0]|0;var z=a+3|0;if(0===(h|0))k=f,f=l,a=z;else{r=h;for(v=0;;)if(m=m+2|0,d[(0+z|0)+v|0]=d[((0+a|0)+(-(k<<8&7936)|0)|0)+m|0]|0,r=r-1|0,0!==(r|0)){var A=m;m=t;t=A;v=v+1|0}else break;a=z+h|0;k=f;f=l}}}else{f=k+1|0;if(10485760<((0+a|0)+f|0)||((0+b|0)+f|0)>(0+g|0)){c=0;break b}d[0+a|0]=c[0+b|0]|0;h=b+1|0;l=a+1|0;if(0===(k|0))k=
b,b=h,h=k,a=l;else for(f=a;;)if(d[0+l|0]=c[0+h|0]|0,b=b+2|0,k=k-1|0,a=f+2|0,0!==(k|0))a=b,m=f,f=l,l=m+2|0,b=h,h=a;else break;f=(k=(0+b|0)<(0+g|0)?1:0)?1:0;k?(k=c[0+b|0]&255,b=h+2|0):k=0}if(0===(f|0))break}c=0+a|0}g=c|0;break;default:g=0}c=new Number(+(g|0));c.toString(10);c=new Uint8Array(g/1|0);if(0!==(g|0))for(d=0;c[d]=x[d]|0,d=d+1|0,(g|0)!==(d|0););g=0;x=c;+x.BYTES_PER_ELEMENT;0!==(g|0)&&(x=x.subarray(+(g>>>0)));return x};var y={d:[null],o:0};new Uint8Array([100,101,99,111,100,101,32,115,116,97,
114,116,0]);new Uint8Array([100,101,99,111,100,101,32,101,110,100,0]);var q="object"===typeof self&&self.self===self&&self||"object"===typeof global&&global.global===global&&global||this;e.promise=Promise.resolve();q.FastLZDecoder=e})();var template={VERSION:"0.1",AUTHOR:"agent.zy",cache:{},isNode:!1,opt_level:1};try{null==window&&(template.isNode=!0)}catch(e){template.isNode=!0}
template.info=function(){template.isNode?console.log("[info] template engine node v"+template.VERSION):console.log("[info] template engine browser v"+template.VERSION);console.log("[info] template author "+template.AUTHOR)};
template.isNode&&(template.trim_r=function(e){for(var n=e.length,p=[],w=0;w<n;w++)"\t"!=e[w]&&"\n"!=e[w]&&e[w]&&p.push(e[w]);return p},template.itor="for foreach if else end EOL".split(" "),template.eval=function(e,n){n=e.split(" ");n=template.trim_r(n);if(0<n.length){var p=n[0];if(-1==template.itor.indexOf(p))return e;switch(p){case "if":return"if "+n[1]+"{";case "else":return"}else{";case "for":return"for(var "+n[1]+" in "+n[3]+") {";case "foreach":return"for(var k in "+n[3]+") { var "+n[1]+"="+
n[3]+"[k];";case "end":return"};";case "EOL":return'tml.push("\\n");'}}return""},template.macro=function(e){e=template.trim_r(e.split(" "));return'section["'+e[0]+'"] = "'+e[1]+'"'},template.opt_trim=function(e,n,p){n=e.length;var w=[";"],u;for(u in p)w.push("var _"+u+'=data["'+u+"\"] || '';");w.unshift(e[0]);e[0]=w.join("");for(p=0;p<n;p++)'tml.push("")'==e[p]&&e.splice(p,1);return e});
function utf8Encode(e){for(var n=e.length,p=[],w=0;w<n;w++)p[w]=e.charCodeAt(w);return new Uint8Array((new Uint16Array(p)).buffer)}function utf8Decode(e){e=new Uint16Array(e.buffer);for(var n="",p=e.length,w=0;w<p;w++)n+=String.fromCharCode(e[w]);return n}
template.load=function(e,n){if(template.isNode){var p=require("fs");p.existsSync(e)&&(e=p.readFileSync(e),template.init(e))}else{var w=new XMLHttpRequest;w.responseType="arraybuffer";w.onreadystatechange=function(){if(4==w.readyState){var u=new Uint8Array(w.response);template.init(u);null!=n&&n()}};w.open("GET",e,!0);w.send(null)}};template.render=function(e,n){if(template.cache[e])return template.cache[e](n)};
template.init=function(e){if(80==e[0]&&75==e[1]){var n=e[2];var p=n+3;for(var w=e.subarray(3,3+n),u=[],y=0;y<n;y++)u[y]=w[y];n=Number(u.join(""));w=e.subarray(p,p+n);p+=n;n=utf8Decode(new Uint8Array(w));try{var q=JSON.parse(n),c;for(c in q){var a=(new FastLZDecoder).decode(new Uint8Array(e.subarray(p+q[c].s,p+q[c].s+q[c].e))),d=utf8Decode(a);n=c;var g=new Function(d);n&&(template.cache[n]=g)}}catch(x){console.log("[error] parse meta error",x)}}else console.log("[error] file is bad .")};
template.isNode&&(template.precompile=function(e,n,p){if(template.isNode){p||(p=".html");var w=require("fs");if(w.existsSync(e)){var u=new Uint8Array(10485760),y=w.readdirSync(e),q=[],c=y.length;if(p&&0<c){for(e=0;e<c;e++)if(-1!=y[e].indexOf(p)){var a=w.readFileSync(y[e]).toString("utf8");a=template.compile(a,"",!1,!0);codes=utf8Encode(a);a=(new FastLZDecoder).encode(codes);q.push({b:a,k:y[e]})}p=0;c=[];y={};for(e=0;e<q.length;e++)c.push(p),y[q[e].k]={s:p,e:q[e].b.length},u.set(q[e].b,p),p+=q[e].b.length;
u=u.slice(0,p);q=u.length;e=JSON.stringify(y);p=utf8Encode(e);c=p.length;y=c.toString().split("");var d=y.length;a=new Uint8Array(3+y.length);a[0]=80;a[1]=75;a[2]=Number(d);for(e=0;e<d;e++)a[3+e]=Number(y[e])>>0;e=new Uint8Array(a.length+c+q);e.set(a,0);e.set(p,a.length);e.set(u,a.length+c);w.writeFileSync(n,e,"utf8")}}}else console.log("[error] browser is not implements.")});
template.compile=function(e,n,p,w){n||(n=0);if(template.cache[n])return template.cache[n];e=e.replace(/\n/g,"\\n");e=e.replace(/\t/g,"");e=e.replace(/\r/g,"");e=e.replace(/"/g,"'");var u=e.length;var y=p?[]:["var tml=[];var data =arguments[0] || {};"];for(var q=!1,c=[],a="",d=0,g,x={},b={},f=0;f<u;f++){g=e.charAt(f);if("{"==g){var k=e.charAt(f+1);switch(k){case "{":case "-":case "*":case "%":case "#":case "(":y.push('tml.push("'+a+'")'),c.push(f+2),d=f,a=""}}if("}"==g)switch(k=e.charAt(f-1),k){case "}":if(g=
c.pop())g=e.substring(g,f-1),k='tml.push(data["'+g+'"]);',y.push("tml.push(_"+g+");"),a="",d=f+2,x[k]=1,b[g]=1;break;case "*":if(g=c.pop())g=e.substring(g,f-1),y.push("tml.push("+g+");"),a="",d=f+2;break;case "%":if(g=c.pop())g=e.substring(g,f-1),y.push(template.eval(g)),a="",d=f+2;break;case "-":if(g=c.pop())g=e.substring(g,f-1),y.push("var section={};"),y.push("var domacro=function(v){for(var k in section){v=v.replace(new RegExp(k,'g'),section[k]);}return v;};"),y.push(template.macro(g)),a="",d=
f+2,q=!0;break;case ")":if(template.isNode){if(g=c.pop())g=e.substring(g,f-1),a="",d=f+2,template.cache[g]||(k=require("fs"),k.existsSync(g)?(k=k.readFileSync(g).toString("utf8"),g=template.compile(k,g,!0),y=y.concat(g)):y.push("tml.push('[error] "+g+" is not include.');"))}else console.log("not implements");break;case "#":a="",d=f+2}else f==u-1&&y.push('tml.push("'+e.substring(d-1,u)+'");'),a+=g}0<template.opt_level&&(y=template.opt_trim(y,x,b));if(p)return y;q?y.push("return domacro(tml.join(''));"):
y.push("return tml.join('');");if(w)return y.join("\n");try{var l=y.join("\n"),h=new Function(l);template.cache[n]=h}catch(m){console.log("[error] syntax error "+m)}return h};template.isNode?exports.template=template:window.template=template;
