var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(d,k,l){if(d==Array.prototype||d==Object.prototype)return d;d[k]=l.value;return d};
$jscomp.getGlobal=function(d){d=["object"==typeof globalThis&&globalThis,d,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var k=0;k<d.length;++k){var l=d[k];if(l&&l.Math==Math)return l}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(d,k){var l=$jscomp.propertyToPolyfillSymbol[k];if(null==l)return d[k];l=d[l];return void 0!==l?l:d[k]};$jscomp.polyfill=function(d,k,l,u){k&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(d,k,l,u):$jscomp.polyfillUnisolated(d,k,l,u))};
$jscomp.polyfillUnisolated=function(d,k,l,u){l=$jscomp.global;d=d.split(".");for(u=0;u<d.length-1;u++){var q=d[u];if(!(q in l))return;l=l[q]}d=d[d.length-1];u=l[d];k=k(u);k!=u&&null!=k&&$jscomp.defineProperty(l,d,{configurable:!0,writable:!0,value:k})};
$jscomp.polyfillIsolated=function(d,k,l,u){var q=d.split(".");d=1===q.length;u=q[0];u=!d&&u in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var y=0;y<q.length-1;y++){var r=q[y];if(!(r in u))return;u=u[r]}q=q[q.length-1];l=$jscomp.IS_SYMBOL_NATIVE&&"es6"===l?u[q]:null;k=k(l);null!=k&&(d?$jscomp.defineProperty($jscomp.polyfills,q,{configurable:!0,writable:!0,value:k}):k!==l&&($jscomp.propertyToPolyfillSymbol[q]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(q):$jscomp.POLYFILL_PREFIX+q,q=
$jscomp.propertyToPolyfillSymbol[q],$jscomp.defineProperty(u,q,{configurable:!0,writable:!0,value:k})))};$jscomp.polyfill("Math.imul",function(d){return d?d:function(k,l){k=Number(k);l=Number(l);var u=k&65535,q=l&65535;return u*q+((k>>>16&65535)*q+u*(l>>>16&65535)<<16>>>0)|0}},"es6","es3");
$jscomp.polyfill("Math.fround",function(d){if(d)return d;if($jscomp.SIMPLE_FROUND_POLYFILL||"function"!==typeof Float32Array)return function(l){return l};var k=new Float32Array(1);return function(l){k[0]=l;return k[0]}},"es6","es3");$jscomp.arrayIteratorImpl=function(d){var k=0;return function(){return k<d.length?{done:!1,value:d[k++]}:{done:!0}}};$jscomp.arrayIterator=function(d){return{next:$jscomp.arrayIteratorImpl(d)}};
$jscomp.makeIterator=function(d){var k="undefined"!=typeof Symbol&&Symbol.iterator&&d[Symbol.iterator];return k?k.call(d):$jscomp.arrayIterator(d)};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(d){function k(){this.batch_=null}function l(r){return r instanceof q?r:new q(function(c,a){c(r)})}if(d&&!$jscomp.FORCE_POLYFILL_PROMISE)return d;k.prototype.asyncExecute=function(r){if(null==this.batch_){this.batch_=[];var c=this;this.asyncExecuteFunction(function(){c.executeBatch_()})}this.batch_.push(r)};var u=$jscomp.global.setTimeout;k.prototype.asyncExecuteFunction=function(r){u(r,0)};k.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var r=
this.batch_;this.batch_=[];for(var c=0;c<r.length;++c){var a=r[c];r[c]=null;try{a()}catch(e){this.asyncThrow_(e)}}}this.batch_=null};k.prototype.asyncThrow_=function(r){this.asyncExecuteFunction(function(){throw r;})};var q=function(r){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var c=this.createResolveAndReject_();try{r(c.resolve,c.reject)}catch(a){c.reject(a)}};q.prototype.createResolveAndReject_=function(){function r(e){return function(g){a||(a=!0,e.call(c,g))}}var c=this,a=!1;
return{resolve:r(this.resolveTo_),reject:r(this.reject_)}};q.prototype.resolveTo_=function(r){if(r===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(r instanceof q)this.settleSameAsPromise_(r);else{a:switch(typeof r){case "object":var c=null!=r;break a;case "function":c=!0;break a;default:c=!1}c?this.resolveToNonPromiseObj_(r):this.fulfill_(r)}};q.prototype.resolveToNonPromiseObj_=function(r){var c=void 0;try{c=r.then}catch(a){this.reject_(a);return}"function"==typeof c?
this.settleSameAsThenable_(c,r):this.fulfill_(r)};q.prototype.reject_=function(r){this.settle_(2,r)};q.prototype.fulfill_=function(r){this.settle_(1,r)};q.prototype.settle_=function(r,c){if(0!=this.state_)throw Error("Cannot settle("+r+", "+c+"): Promise already settled in state"+this.state_);this.state_=r;this.result_=c;this.executeOnSettledCallbacks_()};q.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var r=0;r<this.onSettledCallbacks_.length;++r)y.asyncExecute(this.onSettledCallbacks_[r]);
this.onSettledCallbacks_=null}};var y=new k;q.prototype.settleSameAsPromise_=function(r){var c=this.createResolveAndReject_();r.callWhenSettled_(c.resolve,c.reject)};q.prototype.settleSameAsThenable_=function(r,c){var a=this.createResolveAndReject_();try{r.call(c,a.resolve,a.reject)}catch(e){a.reject(e)}};q.prototype.then=function(r,c){function a(b,f){return"function"==typeof b?function(m){try{e(b(m))}catch(n){g(n)}}:f}var e,g,x=new q(function(b,f){e=b;g=f});this.callWhenSettled_(a(r,e),a(c,g));return x};
q.prototype.catch=function(r){return this.then(void 0,r)};q.prototype.callWhenSettled_=function(r,c){function a(){switch(e.state_){case 1:r(e.result_);break;case 2:c(e.result_);break;default:throw Error("Unexpected state: "+e.state_);}}var e=this;null==this.onSettledCallbacks_?y.asyncExecute(a):this.onSettledCallbacks_.push(a)};q.resolve=l;q.reject=function(r){return new q(function(c,a){a(r)})};q.race=function(r){return new q(function(c,a){for(var e=$jscomp.makeIterator(r),g=e.next();!g.done;g=e.next())l(g.value).callWhenSettled_(c,
a)})};q.all=function(r){var c=$jscomp.makeIterator(r),a=c.next();return a.done?l([]):new q(function(e,g){function x(m){return function(n){b[m]=n;f--;0==f&&e(b)}}var b=[],f=0;do b.push(void 0),f++,l(a.value).callWhenSettled_(x(b.length-1),g),a=c.next();while(!a.done)})};return q},"es6","es3");
(function(){function d(){this.i0=0;this.d=[this]}function k(c,a,e,g,x){var b,f;var m=l([],0,8192,y);if(4>(e|0)){if(0===(e|0))return 0;g[x]=e+255|0;if((((a+e|0)+-2|0)+1|0)>=a)for(b=f=0;;)if(b=b+1|0,g[x+b|0]=c[a+f|0]|0,(a+f|0)<=((a+e|0)+-2|0))f=f+1|0;else break;return e+1|0}for(b=0;m[b]={d:c,o:a},b=b+1|0,8192>(0+b|0););g[x]=31;g[x+1|0]=c[a]|0;g[x+2|0]=c[a+1|0]|0;if((a+2|0)<((a+e|0)+-12|0)){var n=2;f=3;for(b=2;;){a:{var h=b+1|0;var p=c[a+h|0]&255;var w=p<<8|c[a+b|0]&255;var v=c[(a+b|0)+2|0]|0;var t=
m[(w>>>3^w^(v<<8|p))&8191];var z=t.o;var A=a+b|0;var B=A-z|0;m[(w>>>3^w^(v<<8|p))&8191]={d:c,o:a+b|0};if((A|0)===(z|0)||8191<B>>>0)b=c[a+b|0]|0;else if(p=t.d[t.o]|0,w=c[a+b|0]|0,(p&255)===(w&255))if((t.d[t.o+1|0]|0)===(c[a+h|0]&255))if(w=t.d[t.o+2|0]|0,w===(c[(a+b|0)+2|0]|0)){p=B-1|0;v=b+3|0;b:if(0===(p|0))if((a+v|0)<((a+e|0)+-2|0))for(h=3,b=0;;){z=v+b|0;if((t.d[t.o+h|0]&255)===w)if(b=b+1|0,z=v+b|0,h=h+1|0,(a+z|0)<((a+e|0)+-2|0))continue;else h=z;else{h=z;break b}break}else h=v;else if(h=b+4|0,(t.d[t.o+
3|0]|0)===(c[a+v|0]&255))if(w=b+5|0,(t.d[t.o+4|0]|0)===(c[a+h|0]&255)){if(h=b+6|0,(t.d[t.o+5|0]|0)===(c[a+w|0]&255))if(w=b+7|0,(t.d[t.o+6|0]|0)===(c[a+h|0]&255)){if(h=b+8|0,(t.d[t.o+7|0]|0)===(c[a+w|0]&255))if(w=b+9|0,(t.d[t.o+8|0]|0)===(c[a+h|0]&255)){if(h=b+10|0,(t.d[t.o+9|0]|0)===(c[a+w|0]&255))if(w=b+11|0,(t.d[t.o+10|0]|0)===(c[a+h|0]&255))for(h=0,b=11;;){v=w+h|0;if((a+v|0)<((a+e|0)+-2|0)){if(z=h+1|0,h=w+z|0,B=b+1|0,(t.d[t.o+b|0]&255)===(c[a+v|0]&255)){h=z;b=B;continue}}else h=v;break}else h=
w}else h=w}else h=w}else h=w;0===(n|0)?f=f-1|0:g[((x+f|0)+(-n|0)|0)+-1|0]=n+255|0;n=(a+h|0)+-3|0;b=n-A|0;if(262<b>>>0){w=((-263-A|0)+n>>>0)/262|0;n=((n-262|0)-A|0)+(u(w,-262)|0)|0;v=x+f|0;for(t=g;;)if(t[v]=(p>>>8)+224|0,t[v+1|0]=253,t[v+2|0]=p,b=b-262|0,262<b>>>0)v=v+3|0;else break;b=f+3|0;f=b+(u(w,3)|0)|0;b=n}7>b>>>0?(g[x+f|0]=(b<<5)+(p>>>8)|0,v=(x+f|0)+2|0,t=g,b=p,n=2):(g[x+f|0]=(p>>>8)+224|0,g[(x+f|0)+2|0]=p,v=(x+f|0)+3|0,t=g,n=3,b=b+249|0);g[(x+f|0)+1|0]=b;f=f+n|0;n=c[(a+h|0)+-2|0]&255;p=n<<8|
c[(a+h|0)+-3|0]&255;b=h-1|0;m[(p>>>3^p^((c[a+b|0]&255)<<8|n))&8191]={d:c,o:(a+h|0)+-3|0};n=c[a+b|0]&255;p=n<<8|c[(a+h|0)+-2|0]&255;m[(p>>>3^p^((c[a+h|0]&255)<<8|n))&8191]={d:c,o:(a+h|0)+-2|0};t[v]=31;f=f+1|0;n=0;break a}else b=p;else b=p;else b=w;g[x+f|0]=b;n=n+1|0;b=f+1|0;32===(n|0)?(g[x+b|0]=31,f=f+2|0,b=h,n=0):(f=b,b=h)}if(!((a+b|0)<((a+e|0)+-12|0)))break}}else n=2,f=3,b=2;if((a+b|0)<=(((a+e|0)+-2|0)+1|0))for(;;)if(g[x+f|0]=c[a+b|0]|0,n=n+1|0,h=f+1|0,32===(n|0)?(g[x+h|0]=31,f=f+2|0,n=0):f=h,h=
b+1|0,(a+b|0)<=((a+e|0)+-2|0))b=h;else break;0===(n|0)?f=f-1|0:g[((x+f|0)+(-n|0)|0)+-1|0]=n+255|0;return(x+f|0)-x|0}function l(c,a,e,g){for(;a<e;a++)c[a]=g;return c}var u=Math.imul,q=Math.fround;d.prototype.encode=function(c){var a=+c.length;var e=0>a?-a:a;var g=~~(e*q(2.32830644E-10));var x=new Int32Array(4);x[0]=g;e=~~(e%4294967296);x[1]=e;x[2]=0!==(e|0)?g^-1|0:-g|0;x[3]=-e|0;g=x[(0>a?2:0)+1|0]|0;x=new Uint8Array(g+1|0);k(c,0,g,x,0)|0;if(65536>(g|0))c=k(c,0,g,x,0)|0;else{e=x;var b;var f=l([],0,
8192,y);if(4>(g|0))if(0===(g|0))c=0;else{e[0]=g+255|0;if(0<=(((0+g|0)+-2|0)+1|0))for(a=b=0;;)if(a=a+1|0,e[0+a|0]=c[0+b|0]|0,(0+b|0)<=((0+g|0)+-2|0))b=b+1|0;else break;c=g+1|0}else{for(a=0;f[a]={d:c,o:0},a=a+1|0,8192>(0+a|0););e[0]=31;e[1]=c[0]|0;e[2]=c[1]|0;if(2<((0+g|0)+-12|0)){var m=2;b=3;for(a=2;;){c:{d:{var n=c[0+a|0]|0;if((n&255)===(c[(0+a|0)+-1|0]&255)){n&=255;var h=c[(0+a|0)+1|0]|0;var p=c[(0+a|0)+2|0]|0;if((n<<8|n|0)===(p<<8|h|0)){var w=(0+a|0)+2|0;var v=c;p=3;n=1;break d}}else h=c[(0+a|0)+
1|0]|0,p=c[(0+a|0)+2|0]|0,n&=255;var t=h<<8|n;v=f[(t^(p<<8|h))&8191^t>>>3];var z=v.o;var A=0+a|0;n=A-z|0;f[(t^(p<<8|h))&8191^t>>>3]={d:c,o:0+a|0};p=a+1|0;if((A|0)===(z|0)||73724<n>>>0)a=c[0+a|0]|0;else if(h=v.d[v.o]|0,t=c[0+a|0]|0,(h&255)===(t&255))if((v.d[v.o+1|0]|0)===(c[0+p|0]&255))if((v.d[v.o+2|0]|0)===(c[(0+a|0)+2|0]|0))if(8190<n>>>0)if((c[(0+a|0)+3|0]|0)===(v.d[v.o+3|0]|0))if((c[(0+a|0)+4|0]|0)===(v.d[v.o+4|0]|0)){p=5;w=v.o+5|0;v=v.d;break d}else a=h;else a=h;else{p=3;w=v.o+3|0;v=v.d;break d}else a=
h;else a=h;else a=t;e[0+b|0]=a;m=m+1|0;a=b+1|0;32===(m|0)?(e[0+a|0]=31,b=b+2|0,a=p,m=0):(b=a,a=p);break c}z=a+p|0;A=n-1|0;d:if(0===(A|0))if(h=c[(0+z|0)+-1|0]|0,(0+z|0)<((0+g|0)+-2|0))for(p=0;;){if((v[w]&255)===(h&255)){if(p=p+1|0,((0+z|0)+p|0)<((0+g|0)+-2|0)){w=w+1|0;continue}}else break d;break}else p=0;else if((v[w]&255)===(c[0+z|0]&255)){if(p=2,(v[w+1|0]|0)===(c[(0+z|0)+1|0]|0))if(h=p+1|0,(v[w+2|0]|0)===(c[(0+z|0)+p|0]&255)){if(p=h+1|0,(v[w+3|0]|0)===(c[(0+z|0)+h|0]&255))if(h=p+1|0,(v[w+4|0]|0)===
(c[(0+z|0)+p|0]&255)){if(p=h+1|0,(v[w+5|0]|0)===(c[(0+z|0)+h|0]&255))if(h=p+1|0,(v[w+6|0]|0)===(c[(0+z|0)+p|0]&255)){if(p=h+1|0,(v[w+7|0]|0)===(c[(0+z|0)+h|0]&255))for(t=p,p=h,h=0;;){if(((0+z|0)+t|0)<((0+g|0)+-2|0)){p=p+2|0;var B=h+1|0;if((v[(w+8|0)+h|0]&255)===(c[(0+z|0)+t|0]&255)){var C=p;h=B;p=t;t=C;continue}}else p=t;break}}else p=h}else p=h}else p=h}else p=1;p=z+p|0;0===(m|0)?b=b-1|0:e[((0+b|0)+(-m|0)|0)+-1|0]=m+255|0;h=(0+p|0)+-3|0;t=0+a|0;m=h-t|0;if(8191>A>>>0)if(7>m>>>0)e[0+b|0]=(m<<5)+(A>>>
8)|0,e[(0+b|0)+1|0]=A,a=b+2|0;else{e[0+b|0]=(A>>>8)+224|0;a=b+1|0;m=m-7|0;if(254<m>>>0){for(n=(-262-t|0)+h|0;;)if(e[0+a|0]=255,b=b+2|0,m=m-255|0,254<m>>>0)h=a,a=b,b=h;else break;w=0+b|0;v=e;m=(n>>>0)%255|0}else w=0+a|0,v=e,a=b;v[w]=m;e[(0+a|0)+2|0]=A;a=a+3|0}else if(n=n-8192|0,7>m>>>0)e[0+b|0]=(m<<5)+31|0,e[(0+b|0)+1|0]=255,e[(0+b|0)+2|0]=n>>>8,e[(0+b|0)+3|0]=n,a=b+4|0;else{e[0+b|0]=255;a=b+1|0;m=m-7|0;if(254<m>>>0){for(h=(-262-t|0)+h|0;;)if(e[0+a|0]=255,b=b+2|0,m=m-255|0,254<m>>>0)t=a,a=b,b=t;else break;
w=0+b|0;v=e;m=(h>>>0)%255|0}else w=0+a|0,v=e,a=b;v[w]=m;e[(0+a|0)+2|0]=255;e[(0+a|0)+3|0]=n>>>8;e[(0+a|0)+4|0]=n;a=a+5|0}b=c[(0+p|0)+-2|0]&255;m=b<<8|c[(0+p|0)+-3|0]&255;n=p-1|0;f[(m>>>3^m^((c[0+n|0]&255)<<8|b))&8191]={d:c,o:(0+p|0)+-3|0};b=c[0+n|0]&255;m=b<<8|c[(0+p|0)+-2|0]&255;f[(m>>>3^m^((c[0+p|0]&255)<<8|b))&8191]={d:c,o:(0+p|0)+-2|0};e[0+a|0]=31;b=a+1|0;a=n;m=0}if(!((0+a|0)<((0+g|0)+-12|0)))break}}else m=2,b=3,a=2;if((0+a|0)<=(((0+g|0)+-2|0)+1|0))for(;;)if(e[0+b|0]=c[0+a|0]|0,m=m+1|0,n=b+1|
0,32===(m|0)?(e[0+n|0]=31,b=b+2|0,m=0):b=n,n=a+1|0,(0+a|0)<=((0+g|0)+-2|0))a=n;else break;0===(m|0)?b=b-1|0:e[((0+b|0)+(-m|0)|0)+-1|0]=m+255|0;e[0]|=32;c=0+b|0}c|=0}g=c;new Number(+(g|0));c=new Uint8Array(g/1|0);if(0!==(g|0))for(e=0;c[e]=x[e]|0,e=e+1|0,(g|0)!==(e|0););g=0;x=c;+x.BYTES_PER_ELEMENT;0!==(g|0)&&(x=x.subarray(+(g>>>0)));return x};d.prototype.decode=function(c){var a=+c.length;var e=0>a?-a:a;var g=~~(e*q(2.32830644E-10));var x=new Int32Array(4);x[0]=g;e=~~(e%4294967296);x[1]=e;x[2]=0!==
(e|0)?g^-1|0:-g|0;x[3]=-e|0;e=0>a?2:0;g=x[e]|0;e=x[e+1|0]|0;x=new Number(4294967296*+(g>>>0)+ +(e>>>0));x.toString(10);x=new Uint8Array(10485760);switch((c[0]&255)>>>5|0){case 1:b:{g=e;e=x;var b,f;a=c[0]&31;var m=f=1;for(b=0;;){if(31<a>>>0){var n=a<<8&7936;var h=(a>>>5)-1|0;if(6===(h|0))for(h=6;;){var p=c[0+f|0]|0;h=(p&255)+h|0;var w=f+1|0;if(255===(p&255))f=f+1|0;else{f=w;break}}w=c[0+f|0]|0;p=f+1|0;if(7936===(n|0)&&255===(w&255)){n=c[0+p|0]|0;w=c[(0+f|0)+2|0]|0;p=f+3|0;var v=((0+b|0)+(-(((n&255)<<
8)+w|0)|0)|0)+-8191|0;var t=e;n=3}else v=((0+b|0)+(-n|0)|0)+(-(w&255)|0)|0,t=e,n=1;if(10485760<(((0+b|0)+h|0)+3|0)||0>(v+-1|0)){c=0;break b}(0+p|0)<(0+g|0)?(f=f+n|0,a=c[0+p|0]&255,p=f+1|0):m=0;w=t[v+-1|0]|0;e[0+b|0]=w;if(t.length===e.length&&t===e&&v===(0+b|0)){if(e[(0+b|0)+1|0]=w,e[(0+b|0)+2|0]=w,b=b+3|0,0!==(h|0)){f=h;for(n=0;;)if(e[(0+b|0)+n|0]=w,f=f-1|0,0!==(f|0))n=n+1|0;else break;b=b+h|0}}else if(e[(0+b|0)+1|0]=t[v]|0,e[(0+b|0)+2|0]=t[v+1|0]|0,b=b+3|0,0!==(h|0)){f=h;for(n=w=0;;)if(e[(0+b|0)+
w|0]=t[(v+2|0)+n|0]|0,f=f-1|0,0!==(f|0))w=w+1|0,n=n+1|0;else break;b=b+h|0}f=p}else{m=a+1|0;if(10485760<((0+b|0)+m|0)||((0+f|0)+m|0)>(0+g|0)){c=0;break b}e[0+b|0]=c[0+f|0]|0;h=f+1|0;n=b+1|0;if(0===(a|0))a=f,f=h,h=a,b=n;else for(m=b;;)if(e[0+n|0]=c[0+h|0]|0,f=f+2|0,a=a-1|0,b=m+2|0,0!==(a|0))b=m,p=f,f=h,h=p,m=n,n=b+2|0;else break;m=(a=(0+f|0)<(0+g|0)?1:0)?1:0;a?(a=c[0+f|0]&255,f=h+2|0):a=0}if(0===(m|0))break}c=0+b|0}g=c|0;break;case 0:b:{g=e;e=x;m=c[0]&31;b=f=1;for(a=0;;){if(31<m>>>0){h=(m>>>5)-1|0;
6===(h|0)&&(h=(c[0+b|0]&255)+6|0,b=b+1|0);p=-(c[0+b|0]&255)|0;if(10485760<(((0+a|0)+h|0)+3|0)){c=0;break b}t=p-1|0;if(0>(((0+a|0)+(-(m<<8&7936)|0)|0)+t|0)){c=0;break b}n=b+1|0;(0+n|0)<(0+g|0)?(n=c[0+n|0]&255,b=b+2|0,v=f,f=n,n=v):(f=m,b=n,n=0);if(e.length===e.length&&e===e&&(((0+a|0)+(-(m<<8&7936)|0)|0)+p|0)===(0+a|0)){t=e[((0+a|0)+(-(m<<8&7936)|0)|0)+t|0]|0;e[0+a|0]=t;e[(0+a|0)+1|0]=t;e[(0+a|0)+2|0]=t;a=a+3|0;if(0!==(h|0)){m=h;for(p=0;;)if(e[(0+a|0)+p|0]=t,m=m-1|0,0!==(m|0))p=p+1|0;else break;a=a+
h|0}m=f;f=n}else{p=t+1|0;e[0+a|0]=e[((0+a|0)+(-(m<<8&7936)|0)|0)+t|0]|0;v=p+1|0;e[(0+a|0)+1|0]=e[((0+a|0)+(-(m<<8&7936)|0)|0)+p|0]|0;e[(0+a|0)+2|0]=e[((0+a|0)+(-(m<<8&7936)|0)|0)+v|0]|0;var z=a+3|0;if(0===(h|0))m=f,f=n,a=z;else{t=h;for(w=0;;)if(p=p+2|0,e[(0+z|0)+w|0]=e[((0+a|0)+(-(m<<8&7936)|0)|0)+p|0]|0,t=t-1|0,0!==(t|0)){var A=p;p=v;v=A;w=w+1|0}else break;a=z+h|0;m=f;f=n}}}else{f=m+1|0;if(10485760<((0+a|0)+f|0)||((0+b|0)+f|0)>(0+g|0)){c=0;break b}e[0+a|0]=c[0+b|0]|0;h=b+1|0;n=a+1|0;if(0===(m|0))m=
b,b=h,h=m,a=n;else for(f=a;;)if(e[0+n|0]=c[0+h|0]|0,b=b+2|0,m=m-1|0,a=f+2|0,0!==(m|0))a=b,p=f,f=n,n=p+2|0,b=h,h=a;else break;f=(m=(0+b|0)<(0+g|0)?1:0)?1:0;m?(m=c[0+b|0]&255,b=h+2|0):m=0}if(0===(f|0))break}c=0+a|0}g=c|0;break;default:g=0}c=new Number(+(g|0));c.toString(10);c=new Uint8Array(g/1|0);if(0!==(g|0))for(e=0;c[e]=x[e]|0,e=e+1|0,(g|0)!==(e|0););g=0;x=c;+x.BYTES_PER_ELEMENT;0!==(g|0)&&(x=x.subarray(+(g>>>0)));return x};var y={d:[null],o:0};new Uint8Array([100,101,99,111,100,101,32,115,116,97,
114,116,0]);new Uint8Array([100,101,99,111,100,101,32,101,110,100,0]);var r="object"===typeof self&&self.self===self&&self||"object"===typeof global&&global.global===global&&global||this;d.promise=Promise.resolve();r.FastLZDecoder=d})();var template={VERSION:"0.3",AUTHOR:"agent.zy",cache:{},isNode:!1,opt_level:1};try{null==window&&(template.isNode=!0)}catch(d){template.isNode=!0}
template.info=function(){template.isNode?console.log("[info] template engine node v"+template.VERSION):console.log("[info] template engine browser v"+template.VERSION);console.log("[info] template author "+template.AUTHOR)};
template.isNode&&(template.trim_r=function(d){for(var k=d.length,l=[],u=0;u<k;u++)"\t"!=d[u]&&"\n"!=d[u]&&d[u]&&l.push(d[u]);return l},template.invalidate_ipairs=function(d){for(var k=d.length,l=[],u=[],q=1;q<k&&"in"!=d[q];q++)u.push(d[q]);k=u.join("").split(",");l[0]=d[0];l[1]=k[0];l[2]=k[1];l[3]="in";l[4]=d[3];l[5]="do";return l},template.invalidate_if=function(d){for(var k=d.length,l=[],u=[],q=1;q<k&&"do"!=d[q];q++)u.push(d[q]);l[0]=d[0];l[1]=u.join("");l[2]="do";return l},template.itor="for foreach ipairs if else end EOL".split(" "),
template.eval=function(d,k){k=d.split(" ");k=template.trim_r(k);if(0<k.length){var l=k[0];if(-1==template.itor.indexOf(l))return d;switch(l){case "if":return k=template.invalidate_if(k),"if "+k[1]+"{";case "ipairs":return k=template.invalidate_ipairs(k),d=[],d[0]="var $len = "+k[4]+".length;",d[1]="for(var "+k[1]+"=0; "+k[1]+"<$len;"+k[1]+"++){",d[2]="var "+k[2]+"="+k[4]+"["+k[1]+"];",d.join("\n");case "else":return"}else{";case "for":return"for(var "+k[1]+" in "+k[3]+") {";case "foreach":return"for(var k in "+
k[3]+") { var "+k[1]+"="+k[3]+"[k];";case "end":return"};";case "EOL":return'tml.push("\\n");'}}return""},template.macro=function(d){d=template.trim_r(d.split(" "));return'section["'+d[0]+'"] = "'+d[1]+'"'},template.opt_trim2=function(d){for(var k=d.length,l=[],u=[],q="",y=0;y<k;y++)-1==d[y].indexOf("tml.push")?(q+=d[y],0<u.length&&(l.push("tml.push("+u.join("+")+");"),u=[])):(q&&l.push(q),l.push(d[y]),q="");q&&l.push(q);return l},template.opt_trim=function(d,k,l){k=d.length;var u=[";"],q;for(q in l)u.push("var _"+
q+'=data["'+q+"\"] || '';");u.unshift(d[0]);d[0]=u.join("");for(l=0;l<k;l++)'tml.push("")'==d[l]&&d.splice(l,1),'tml.push(" ")'==d[l]&&d.splice(l,1);return d});function utf8Encode(d){for(var k=d.length,l=[],u=0;u<k;u++)l[u]=d.charCodeAt(u);return new Uint8Array((new Uint16Array(l)).buffer)}function utf8Decode(d){d=new Uint16Array(d.buffer);for(var k="",l=d.length,u=0;u<l;u++)k+=String.fromCharCode(d[u]);return k}
template.load=function(d,k){if(template.isNode){var l=require("fs");l.existsSync(d)&&(d=l.readFileSync(d),template.init(d))}else{var u=new XMLHttpRequest;u.responseType="arraybuffer";u.onreadystatechange=function(){if(4==u.readyState){var q=new Uint8Array(u.response);template.init(q);null!=k&&k()}};u.open("GET",d,!0);u.send(null)}};template.render=function(d,k){if(template.cache[d])return template.cache[d](k)};
template.init=function(d){if(80==d[0]&&75==d[1]){var k=d[2];var l=k+3;for(var u=d.subarray(3,3+k),q=[],y=0;y<k;y++)q[y]=u[y];k=Number(q.join(""));u=d.subarray(l,l+k);l+=k;k=utf8Decode(new Uint8Array(u));try{var r=JSON.parse(k),c;for(c in r){var a=(new FastLZDecoder).decode(new Uint8Array(d.subarray(l+r[c].s,l+r[c].s+r[c].e))),e=utf8Decode(a);k=c;var g=new Function(e);k&&(template.cache[k]=g)}}catch(x){console.log("[error] parse meta error",x)}}else console.log("[error] file is bad .")};
template.isNode&&(template.precompile=function(d,k,l){if(template.isNode){l||(l=".html");var u=require("fs");if(u.existsSync(d)){var q=new Uint8Array(10485760),y=u.readdirSync(d),r=[],c=y.length;if(l&&0<c){for(d=0;d<c;d++)if(-1!=y[d].indexOf(l)){var a=u.readFileSync(y[d]).toString("utf8");a=template.compile(a,"",!1,!0);codes=utf8Encode(a);a=(new FastLZDecoder).encode(codes);r.push({b:a,k:y[d]})}l=0;c=[];y={};for(d=0;d<r.length;d++)c.push(l),y[r[d].k]={s:l,e:r[d].b.length},q.set(r[d].b,l),l+=r[d].b.length;
q=q.slice(0,l);r=q.length;d=JSON.stringify(y);l=utf8Encode(d);c=l.length;y=c.toString().split("");var e=y.length;a=new Uint8Array(3+y.length);a[0]=80;a[1]=75;a[2]=Number(e);for(d=0;d<e;d++)a[3+d]=Number(y[d])>>0;d=new Uint8Array(a.length+c+r);d.set(a,0);d.set(l,a.length);d.set(q,a.length+c);u.writeFileSync(k,d,"utf8")}}}else console.log("[error] browser is not implements.")});
template.compile=function(d,k,l,u){k||(k=0);if(template.cache[k])return template.cache[k];d=d.replace(/\n/g,"\\n");d=d.replace(/\t/g,"");d=d.replace(/\r/g,"");d=d.replace(/"/g,"'");var q=d.length;var y=l?[]:["var tml=[];var data =arguments[0] || {};"];for(var r=!1,c=[],a="",e=0,g,x={},b={},f=0;f<q;f++){g=d.charAt(f);if("{"==g){var m=d.charAt(f+1);switch(m){case "{":case "-":case "*":case "%":case "#":case "(":y.push('tml.push("'+a+'")'),c.push(f+2),e=f,a=""}}if("}"==g)switch(m=d.charAt(f-1),m){case "}":if(g=
c.pop())g=d.substring(g,f-1),m='tml.push(data["'+g+'"]);',y.push("tml.push(_"+g+");"),a="",e=f+2,x[m]=1,b[g]=1;break;case "*":if(g=c.pop())g=d.substring(g,f-1),y.push("tml.push("+g+");"),a="",e=f+2;break;case "%":if(g=c.pop())g=d.substring(g,f-1),y.push(template.eval(g)),a="",e=f+2;break;case "-":if(g=c.pop())g=d.substring(g,f-1),y.push("var section={};"),y.push("var domacro=function(v){for(var k in section){v=v.replace(new RegExp(k,'g'),section[k]);}return v;};"),y.push(template.macro(g)),a="",e=
f+2,r=!0;break;case ")":if(template.isNode){if(g=c.pop())g=d.substring(g,f-1),a="",e=f+2,template.cache[g]||(m=require("fs"),m.existsSync(g)?(m=m.readFileSync(g).toString("utf8"),g=template.compile(m,g,!0),y=y.concat(g)):y.push("tml.push('[error] "+g+" is not include.');"))}else console.log("not implements");break;case "#":a="",e=f+2}else f==q-1&&y.push('tml.push("'+d.substring(e-1,q)+'");'),a+=g}0<template.opt_level&&(y=template.opt_trim(y,x,b));if(l)return y;r?y.push("return domacro(tml.join(''));"):
y.push("return tml.join('');");if(u)return y.join("\n");y=template.opt_trim2(y);try{var n=y.join("\n"),h=new Function(n);template.cache[k]=h}catch(p){console.log("[error] syntax error "+p)}return h};template.isNode?exports.template=template:window.template=template;
